<!doctype html><html lang="es"><head><meta charset="UTF-8"><style>
@page{margin:42px 46px 58px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:10.5px;line-height:1.5;margin:0}h1,h2,h3,p{margin:0}.header{border-bottom:3px solid {{ $accent }};padding-bottom:16px;margin-bottom:20px;min-height:82px}.name{font-size:27px;color:{{ $accent }};letter-spacing:-.5px}.title{font-size:12px;color:#4b5563;margin-top:4px}.contact{font-size:9px;color:#6b7280;margin-top:8px}.photo{float:right;width:82px;height:82px;border-radius:50%;object-fit:cover;border:4px solid white;margin:-5px 0 8px 18px}.section{margin:0 0 17px;page-break-inside:avoid}.section-title{font-size:12px;text-transform:uppercase;letter-spacing:1.2px;color:{{ $accent }};border-bottom:1px solid #d1d5db;padding-bottom:4px;margin-bottom:9px}.item{margin-bottom:10px;page-break-inside:avoid}.item-title{font-size:11px;font-weight:bold}.muted{color:#6b7280}.tags span{display:inline-block;border:1px solid #d1d5db;border-radius:10px;padding:2px 7px;margin:0 4px 4px 0}.footer{position:fixed;left:0;right:0;bottom:-38px;border-top:1px solid #d1d5db;padding-top:7px;text-align:center;font-size:8px;color:#6b7280}.footer strong{color:{{ $accent }}}.modern .header{background:{{ $accent }};color:white;margin:-42px -46px 22px;padding:28px 46px 22px;border:0}.modern .name,.modern .title,.modern .contact{color:white}.modern .section-title{background:#ecfdf5;border:0;padding:6px 8px}.minimal .header{border-bottom:1px solid #111827}.minimal .name{font-weight:normal;color:#111827}.minimal .section-title{color:#111827;border:0;padding:0}.classic .header{text-align:center}.executive .header{background:#172554;color:white;margin:-42px -46px 22px;padding:27px 46px 20px;border:0}.executive .name,.executive .title,.executive .contact{color:white}.executive .section-title{color:#172554}.creative .header{border-left:12px solid {{ $accent }};padding-left:18px;background:#fff7ed}.creative .section-title{border:0;background:#fff7ed;padding:6px 9px}.creative .photo{border-color:{{ $accent }}}.compact{font-size:9.5px}.compact .header{border-bottom:5px solid {{ $accent }}}.compact .section{margin-bottom:11px}.compact .photo{border-radius:8px}
</style></head><body class="{{ $theme }}"><footer class="footer">Currículum creado con <strong>EmpléateRD</strong> · empleaterd.com</footer><header class="header">@if(($showPhoto ?? false) && $photo)<img class="photo" src="{{ $photo }}" alt="Fotografía">@endif<h1 class="name">{{ $user->name }}</h1><p class="title">{{ $profile->professional_title ?: 'Perfil profesional' }}</p><p class="contact">{{ $user->email }} @if($user->phone) · {{ $user->phone }} @endif @if($profile->city || $profile->province) · {{ collect([$profile->city,$profile->province])->filter()->join(', ') }} @endif @if($profile->portfolio_url) · {{ $profile->portfolio_url }} @endif</p></header>
@if($profile->summary)<section class="section"><h2 class="section-title">Perfil</h2><p>{{ $profile->summary }}</p></section>@endif
@if($profile->experience)<section class="section"><h2 class="section-title">Experiencia</h2>@foreach($profile->experience as $item)<div class="item"><p class="item-title">{{ $item['role'] ?? '' }} · {{ $item['company'] ?? '' }}</p><p class="muted">{{ $item['period'] ?? '' }}</p>@if($item['description'] ?? null)<p>{{ $item['description'] }}</p>@endif</div>@endforeach</section>@endif
@if($profile->education)<section class="section"><h2 class="section-title">Educación</h2>@foreach($profile->education as $item)<div class="item"><p class="item-title">{{ $item['degree'] ?? '' }}</p><p>{{ $item['institution'] ?? '' }} <span class="muted">{{ $item['period'] ?? '' }}</span></p></div>@endforeach</section>@endif
@if($profile->skills)<section class="section"><h2 class="section-title">Habilidades</h2><div class="tags">@foreach($profile->skills as $skill)<span>{{ $skill }}</span>@endforeach</div></section>@endif
@if($profile->languages)<section class="section"><h2 class="section-title">Idiomas</h2><p>{{ implode(' · ', $profile->languages) }}</p></section>@endif
@if($profile->certifications)<section class="section"><h2 class="section-title">Certificaciones</h2><p>{{ implode(' · ', $profile->certifications) }}</p></section>@endif
</body></html>
