<?php
namespace Tests\Feature;
use App\Models\CandidateDocument;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class CandidateProfileTest extends TestCase{use RefreshDatabase;
 public function test_candidate_can_update_profile_and_preferences():void{$user=User::factory()->create(['account_type'=>'candidate']);$response=$this->actingAs($user,'sanctum')->putJson('/api/v1/candidate/profile',['professional_title'=>'Desarrolladora frontend','province'=>'Santiago','desired_roles'=>['Frontend Developer'],'preferred_modalities'=>['Remoto','Híbrido'],'salary_expectation'=>80000,'availability'=>'15 días','skills'=>['React','TypeScript']]);$response->assertOk()->assertJsonPath('data.professional_title','Desarrolladora frontend');$this->assertDatabaseHas('candidate_profiles',['user_id'=>$user->id,'province'=>'Santiago']);}
 public function test_candidate_can_save_partial_cv_rows_as_draft():void{$user=User::factory()->create(['account_type'=>'candidate']);$this->actingAs($user,'sanctum')->putJson('/api/v1/candidate/profile',['experience'=>[['role'=>'Desarrolladora','company'=>'','period'=>'','description'=>'']], 'education'=>[['degree'=>'','institution'=>'','period'=>'']]])->assertOk()->assertJsonCount(1,'data.experience')->assertJsonCount(0,'data.education');}
 public function test_company_account_cannot_use_candidate_profile():void{$user=User::factory()->create(['account_type'=>'company']);$this->actingAs($user,'sanctum')->getJson('/api/v1/candidate/profile')->assertForbidden();}
 public function test_candidate_document_is_private_to_owner():void{Storage::fake('local');$owner=User::factory()->create(['account_type'=>'candidate']);$other=User::factory()->create(['account_type'=>'candidate']);$upload=$this->actingAs($owner,'sanctum')->post('/api/v1/candidate/documents',['kind'=>'cv','document'=>UploadedFile::fake()->create('cv.pdf',100,'application/pdf')]);$upload->assertCreated();$document=CandidateDocument::first();Storage::disk('local')->assertExists($document->path);$this->actingAs($other,'sanctum')->get('/api/v1/candidate/documents/'.$document->id.'/download')->assertNotFound();}
 public function test_candidate_can_upload_private_cv_photo():void{Storage::fake('local');$user=User::factory()->create(['account_type'=>'candidate']);$response=$this->actingAs($user,'sanctum')->post('/api/v1/candidate/cv/photo',['photo'=>UploadedFile::fake()->image('perfil.jpg',500,500)]);$response->assertOk()->assertJsonPath('data.has_photo',true);Storage::disk('local')->assertExists($user->candidateProfile->photo_path);}
 public function test_cv_analyzer_returns_score_and_recommendations():void{$user=User::factory()->create(['account_type'=>'candidate','phone'=>'8095550101']);$user->candidateProfile()->create(['professional_title'=>'Desarrolladora frontend','summary'=>str_repeat('Resumen profesional con experiencia y resultados. ',4),'skills'=>['React','TypeScript','Laravel','Git','CSS'],'languages'=>['Español'],'experience'=>[['role'=>'Developer','company'=>'Acme','period'=>'2024','description'=>'Aumenté la conversión un 25%']],'education'=>[['degree'=>'Ingeniería','institution'=>'Universidad','period'=>'2020']],'portfolio_url'=>'https://example.com']);$this->actingAs($user,'sanctum')->getJson('/api/v1/candidate/cv/analyze')->assertOk()->assertJsonStructure(['data'=>['score','level','strengths','improvements','summary']])->assertJsonPath('data.level','Excelente');}
}
