<?php
namespace Tests\Feature;
use App\Models\Company;use App\Models\Job;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class JobApplicationTest extends TestCase{use RefreshDatabase;
 private function job():Job{$company=Company::create(['name'=>'Caribe Digital','slug'=>'caribe-digital','status'=>'active']);return Job::create(['company_id'=>$company->id,'slug'=>'frontend-react','title'=>'Frontend React','summary'=>'Vacante de prueba','location'=>'Santo Domingo','modality'=>'Híbrido','contract_type'=>'Tiempo completo','status'=>'active','published_at'=>now(),'expires_at'=>now()->addDays(30)]);}
 public function test_candidate_can_apply_with_profile_snapshot():void{$user=User::factory()->create(['account_type'=>'candidate']);$user->candidateProfile()->create(['professional_title'=>'Frontend Developer','province'=>'Santiago']);$job=$this->job();$response=$this->actingAs($user,'sanctum')->postJson('/api/v1/candidate/jobs/'.$job->slug.'/applications',['cover_letter'=>'Me interesa la posición.']);$response->assertCreated()->assertJsonPath('data.status','submitted');$this->assertDatabaseHas('job_applications',['job_id'=>$job->id,'user_id'=>$user->id,'status'=>'submitted']);}
 public function test_candidate_cannot_apply_twice():void{$user=User::factory()->create(['account_type'=>'candidate']);$user->candidateProfile()->create(['professional_title'=>'Developer']);$job=$this->job();$this->actingAs($user,'sanctum')->postJson('/api/v1/candidate/jobs/'.$job->slug.'/applications')->assertCreated();$this->actingAs($user,'sanctum')->postJson('/api/v1/candidate/jobs/'.$job->slug.'/applications')->assertUnprocessable()->assertJsonValidationErrors('job');}
 public function test_candidate_can_withdraw_active_application():void{$user=User::factory()->create(['account_type'=>'candidate']);$user->candidateProfile()->create(['professional_title'=>'Developer']);$job=$this->job();$id=$this->actingAs($user,'sanctum')->postJson('/api/v1/candidate/jobs/'.$job->slug.'/applications')->json('data.id');$this->actingAs($user,'sanctum')->patchJson('/api/v1/candidate/applications/'.$id.'/withdraw')->assertOk()->assertJsonPath('data.status','withdrawn');}
}
