<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\User; use Illuminate\Auth\Events\PasswordReset; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Facades\Log; use Illuminate\Support\Facades\Password; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Illuminate\Validation\Rules; use Illuminate\Validation\ValidationException; use Throwable;
class AuthController extends Controller {
 public function register(Request $request):JsonResponse {$data=$request->validate(['name'=>['required','string','max:120'],'email'=>['required','email:rfc','max:190','unique:users,email'],'phone'=>['nullable','string','max:30'],'account_type'=>['required',Rule::in(['candidate','company'])],'password'=>['required','confirmed',Rules\Password::defaults()],'terms'=>['accepted']]);$user=User::create($data);try{$user->sendEmailVerificationNotification();}catch(Throwable $exception){Log::error('No fue posible enviar la verificación al registrar.',['user_id'=>$user->id,'exception'=>$exception->getMessage()]);}$response=$this->payload($user);$response['message']='Cuenta creada. Revisa tu correo para verificarla.';return response()->json($response,201);}
 public function login(Request $request):JsonResponse {$data=$request->validate(['email'=>['required','email'],'password'=>['required','string']]);$user=User::where('email',$data['email'])->first();if(!$user||!Hash::check($data['password'],$user->password)){throw ValidationException::withMessages(['email'=>['Las credenciales no son válidas.']]);}$user->tokens()->delete();return response()->json($this->payload($user));}
 public function user(Request $request):JsonResponse{return response()->json(['data'=>$this->userData($request->user())]);}
 public function logout(Request $request):JsonResponse{$request->user()->currentAccessToken()?->delete();return response()->json(['message'=>'Sesión cerrada correctamente.']);}
 public function forgotPassword(Request $request):JsonResponse{$request->validate(['email'=>['required','email']]);Password::sendResetLink($request->only('email'));return response()->json(['message'=>'Si el correo está registrado, enviaremos las instrucciones.']);}
 public function resetPassword(Request $request):JsonResponse{$data=$request->validate(['token'=>['required'],'email'=>['required','email'],'password'=>['required','confirmed',Rules\Password::defaults()]]);$status=Password::reset($data,function(User $user,string $password):void{$user->forceFill(['password'=>Hash::make($password),'remember_token'=>Str::random(60)])->save();$user->tokens()->delete();event(new PasswordReset($user));});if($status!==Password::PASSWORD_RESET){throw ValidationException::withMessages(['email'=>[__($status)]]);}return response()->json(['message'=>'Contraseña actualizada correctamente.']);}
 private function payload(User $user):array{return ['data'=>['user'=>$this->userData($user),'token'=>$user->createToken('web')->plainTextToken]];}
 private function userData(User $user):array{return ['id'=>$user->id,'name'=>$user->name,'email'=>$user->email,'phone'=>$user->phone,'account_type'=>$user->account_type,'email_verified'=>$user->hasVerifiedEmail(),'is_admin'=>$user->is_admin];}
}
