<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class CandidateProfileController extends Controller{
 public function show(Request $request):JsonResponse{$this->candidateOnly($request);$profile=$request->user()->candidateProfile()->firstOrCreate();return response()->json(['data'=>$this->payload($profile)]);}
 public function update(Request $request):JsonResponse{$this->candidateOnly($request);$data=$request->validate(['professional_title'=>['nullable','string','max:120'],'summary'=>['nullable','string','max:2000'],'province'=>['nullable','string','max:100'],'city'=>['nullable','string','max:100'],'desired_roles'=>['nullable','array','max:10'],'desired_roles.*'=>['string','max:100'],'interest_areas'=>['nullable','array','max:10'],'interest_areas.*'=>['string','max:100'],'preferred_modalities'=>['nullable','array'],'preferred_modalities.*'=>[Rule::in(['Presencial','Remoto','Híbrido'])],'preferred_provinces'=>['nullable','array','max:10'],'preferred_provinces.*'=>['string','max:100'],'salary_expectation'=>['nullable','integer','min:0','max:10000000'],'availability'=>['nullable',Rule::in(['Inmediata','15 días','30 días','A convenir'])],'employment_types'=>['nullable','array'],'employment_types.*'=>[Rule::in(['Tiempo completo','Medio tiempo','Contrato','Freelance'])],'willing_to_relocate'=>['nullable','boolean'],'skills'=>['nullable','array','max:30'],'skills.*'=>['string','max:80'],'languages'=>['nullable','array','max:10'],'languages.*'=>['string','max:80'],'experience'=>['nullable','array','max:15'],'experience.*.role'=>['required_with:experience','string','max:120'],'experience.*.company'=>['required_with:experience','string','max:120'],'experience.*.period'=>['nullable','string','max:80'],'experience.*.description'=>['nullable','string','max:1000'],'education'=>['nullable','array','max:15'],'education.*.degree'=>['required_with:education','string','max:150'],'education.*.institution'=>['required_with:education','string','max:150'],'education.*.period'=>['nullable','string','max:80'],'certifications'=>['nullable','array','max:15'],'certifications.*'=>['string','max:150'],'portfolio_url'=>['nullable','url','max:255']]);$profile=$request->user()->candidateProfile()->updateOrCreate([], $data);return response()->json(['data'=>$this->payload($profile),'message'=>'Perfil actualizado.']);}
 private function payload($profile):array{$fields=['professional_title','summary','province','desired_roles','interest_areas','preferred_modalities','preferred_provinces','availability','skills','languages'];$completed=collect($fields)->filter(fn($field)=>filled($profile->{$field}))->count();return [...$profile->toArray(),'completion'=>($completed*10)];}
 private function candidateOnly(Request $request):void{abort_unless($request->user()->account_type==='candidate',403,'Esta función es exclusiva para candidatos.');}
}
