<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\JobApplication;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;
class CompanyCandidateController extends Controller{
private const STATUSES=['submitted','viewed','evaluating','shortlisted','interview','offer','hired','rejected'];
public function index(Request $r):JsonResponse{$company=$this->company($r,false);$query=JobApplication::with('job:id,company_id,title,slug','user:id,name,email,phone')->whereHas('job',fn($q)=>$q->where('company_id',$company->id));if($r->filled('job_id'))$query->where('job_id',$r->integer('job_id'));if($r->filled('status'))$query->where('status',$r->string('status'));return response()->json(['data'=>$query->latest('applied_at')->get()]);}
public function show(Request $r,JobApplication $application):JsonResponse{$this->owns($r,$application,false);$relations=['job:id,company_id,title,slug','user:id,name,email,phone','document:id,user_id,original_name,mime_type','messages.sender:id,name,account_type','interviews'];$application->load($relations);$application->messages()->where('sender_id','!=',$r->user()->id)->whereNull('read_at')->update(['read_at'=>now()]);if($application->status==='submitted')$application->update(['status'=>'viewed']);return response()->json(['data'=>$application->fresh()->load($relations)]);}
public function updateStatus(Request $r,JobApplication $application):JsonResponse{$this->owns($r,$application,true);$data=$r->validate(['status'=>['required',Rule::in(self::STATUSES)]]);abort_if(in_array($application->status,['withdrawn','hired','rejected']),422,'El proceso ya está cerrado.');$application->update($data);return response()->json(['data'=>$application,'message'=>'Estado de la candidatura actualizado.']);}
public function message(Request $r,JobApplication $application):JsonResponse{$this->owns($r,$application,true);$data=$r->validate(['body'=>['required','string','max:5000']]);$message=$application->messages()->create(['sender_id'=>$r->user()->id,'body'=>$data['body']]);return response()->json(['data'=>$message->load('sender:id,name,account_type'),'message'=>'Mensaje enviado.'],201);}
public function interview(Request $r,JobApplication $application):JsonResponse{$this->owns($r,$application,true);$data=$r->validate(['title'=>['required','string','max:150'],'scheduled_at'=>['required','date','after:now'],'duration_minutes'=>['required','integer','min:15','max:480'],'format'=>['required',Rule::in(['video','phone','in_person'])],'location_or_link'=>['nullable','string','max:500'],'notes'=>['nullable','string','max:2000']]);$interview=$application->interviews()->create([...$data,'created_by'=>$r->user()->id,'status'=>'scheduled']);$application->update(['status'=>'interview']);return response()->json(['data'=>$interview,'message'=>'Entrevista programada.'],201);}
public function document(Request $r,JobApplication $application){$this->owns($r,$application,false);$document=$application->document;if($document&&Storage::disk('local')->exists($document->path))return Storage::disk('local')->download($document->path,$document->original_name);$snapshot=$application->profile_snapshot;$profile=json_decode(json_encode($snapshot['profile']??[]));$user=(object)['name'=>$snapshot['name']??$application->user->name,'email'=>$snapshot['email']??$application->user->email,'phone'=>$snapshot['phone']??$application->user->phone];return Pdf::loadView('pdf.cv.classic',['user'=>$user,'profile'=>$profile,'photo'=>null])->setPaper('a4')->download('cv-'.str($user->name)->slug().'-empleaterd.pdf');}
private function company(Request $r,bool $write){abort_unless($r->user()->account_type==='company',403);$company=$r->user()->companies()->wherePivot('status','active')->first();abort_unless($company,422);$role=$company->members()->whereKey($r->user()->id)->first()?->pivot->role;if($write)abort_unless(in_array($role,['owner','admin','recruiter']),403);return$company;}private function owns(Request $r,JobApplication $application,bool $write):void{$company=$this->company($r,$write);abort_unless($application->job()->where('company_id',$company->id)->exists(),404);}}
