<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\CandidateDocument;use App\Models\Job;use App\Models\JobApplication;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Validation\ValidationException;
class JobApplicationController extends Controller{
 public function index(Request $request):JsonResponse{$this->candidateOnly($request);$applications=$request->user()->jobApplications()->with('job.company')->latest('applied_at')->get()->map(fn(JobApplication $a)=>$this->payload($a));return response()->json(['data'=>$applications]);}
 public function store(Request $request,Job $job):JsonResponse{$this->candidateOnly($request);abort_unless($job->status==='active'&&(!$job->expires_at||$job->expires_at->isFuture()),404);$data=$request->validate(['candidate_document_id'=>['nullable','integer'],'cover_letter'=>['nullable','string','max:3000']]);if(isset($data['candidate_document_id'])){$document=CandidateDocument::whereKey($data['candidate_document_id'])->where('user_id',$request->user()->id)->first();if(!$document)throw ValidationException::withMessages(['candidate_document_id'=>['El documento seleccionado no es válido.']]);}$profile=$request->user()->candidateProfile; if(!$profile)throw ValidationException::withMessages(['profile'=>['Completa tu perfil antes de postularte.']]);if($request->user()->jobApplications()->where('job_id',$job->id)->exists())throw ValidationException::withMessages(['job'=>['Ya te postulaste a esta vacante.']]);$snapshot=['name'=>$request->user()->name,'email'=>$request->user()->email,'phone'=>$request->user()->phone,'profile'=>$profile->toArray()];$application=$request->user()->jobApplications()->create([...$data,'job_id'=>$job->id,'status'=>'submitted','profile_snapshot'=>$snapshot,'applied_at'=>now()]);$application->load('job.company');return response()->json(['data'=>$this->payload($application),'message'=>'Postulación enviada correctamente.'],201);}
 public function withdraw(Request $request,JobApplication $application):JsonResponse{$this->candidateOnly($request);abort_unless($application->user_id===$request->user()->id,404);if(in_array($application->status,['hired','rejected','withdrawn'],true))throw ValidationException::withMessages(['status'=>['Esta postulación ya no puede retirarse.']]);$application->update(['status'=>'withdrawn','withdrawn_at'=>now()]);return response()->json(['data'=>$this->payload($application->load('job.company')),'message'=>'Postulación retirada.']);}
 private function payload(JobApplication $a):array{return ['id'=>$a->id,'status'=>$a->status,'cover_letter'=>$a->cover_letter,'applied_at'=>$a->applied_at,'withdrawn_at'=>$a->withdrawn_at,'job'=>['slug'=>$a->job->slug,'title'=>$a->job->title,'company'=>$a->job->company->name,'location'=>$a->job->location]];}
 private function candidateOnly(Request $request):void{abort_unless($request->user()->account_type==='candidate',403);}
}
